# Generated by Django 2.2.13 on 2020-09-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (("basic_access", "Can access this app"),),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Distribution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(default="")),
                ("apps", models.TextField(default="")),
                ("installed_version", models.CharField(default="", max_length=64)),
                ("latest_version", models.CharField(default="", max_length=64)),
                (
                    "is_outdated",
                    models.BooleanField(db_index=True, default=None, null=True),
                ),
                ("website_url", models.TextField(default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
