# Generated by Django 2.2.13 on 2020-09-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("package_monitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="distribution",
            name="used_by",
            field=models.TextField(
                default="",
                help_text="List of other distribution packages using this package (JSON)",
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="apps",
            field=models.TextField(
                default="",
                help_text="List of installed Django apps included in this package (JSON)",
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="description",
            field=models.TextField(default="", help_text="Description of this package"),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="installed_version",
            field=models.CharField(
                default="",
                help_text="Currently installed version of this package",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="is_outdated",
            field=models.BooleanField(
                db_index=True,
                default=None,
                help_text="A package is outdated when there is a newer stable version available",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="latest_version",
            field=models.CharField(
                default="",
                help_text="Latest stable version available for this package",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="name",
            field=models.CharField(
                help_text="Name of this package", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Date & time this data was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="website_url",
            field=models.TextField(
                default="", help_text="URL to the home page of this package"
            ),
        ),
    ]
