# Generated by Django 2.2.16 on 2020-09-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("package_monitor", "0002_distribution_used_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="distribution",
            name="has_installed_apps",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this package has installed Django apps",
            ),
        ),
    ]
